### ISSUE TITLE
Dosen't work in python 3.x

### ISSUE THREAD

**Issue by erikkjellgren** [steinmanngroup/molecool#1]
I cannot get it to work with Python 3.x
New projects should support Python 3 over Python 2.
Python 2 will soon be out of maintenances.
https://pythonclock.org/

**Comment by cstein** [comment]
"soon" :) 

anyways - at some point it will support Python 3. only just started working on it.

**Comment by cstein** [comment]
Apart from the openbabel support, I have now verified that py.test with python 3 works in 9b3e92

can you please try it out @Melisius and report back what is not working with python 3 with a minimal test case that breaks?!

**Comment by cstein** [comment]
Ok, now verified that it works with python versions 2.7, 3.5 and 3.6 in travis: https://travis-ci.org/steinmanngroup/molecool by commit e3500bcbe6e6db977c1f03731dc3f39b70263516
